### ISSUE TITLE
TopographyAnalyzer and VoronoiInterstitialGenerator not able to identify octahedral sites for bcc structure

### ISSUE THREAD

**Issue by drakeyu** [materialsproject/pymatgen-analysis-defects#102]
Hi! I am currently using VoronoiInterstitialGenerator to get all octahedral and tetrahedral sites from a bcc structure. After using VoronoiInterstitialGenerator it is only able to give me tetrahedral sites. Is there any specific change I need to make the code work? Thanks for any help that can be provided!

**Comment by jmmshn** [comment]
Can you try to use the charge density based InterstitialGenerator, in my testing this works much much better.
at finding high-symmetry sites.
https://www.nature.com/articles/s41524-020-00422-3

This was bascially develped because the other site finders don't really work well.
https://github.com/materialsproject/pymatgen-analysis-defects/blob/a6f2191e3161ebf3a699c1054bc551ac24146a0d/pymatgen/analysis/defects/generators.py#L332-L343
